config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def create 
		todos = Todo.new(todo_params)
		todos.save
		redirect_to root_path
	end

	def destroy
		todo = Todo.find(params[:id])
		todo.destroy
		redirect_to root_path
	end

	private
		def todo_params
			params.require(:todo).permit(:description, :priority)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoajax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>My Todo List </h1>

<%= form_for Todo.new do |f| %>
	<div class="form-group">
	<%= f.text_field :description, placeholder: "what needs doing?" %>
	</div>

	<div class="form-group">
	<%= f.text_field :priority, placeholder: "priority level" %>
	</div>

	<div class= "form-group">
	<%= f.submit%>
	</div>
	<% end %>

<ul>
	<% @todos.each do |todo| %>
  	<li>
    	<%= todo.description %><br>
    	<strong>priority: </strong><%= todo.priority %><br>
    	<%= link_to "done", todo_path(todo), method: 'delete' %>
  	</li>
	<% end %>
</ul>